server:
  port: 8083

spring:
  application:
    name: 4-Admin-API

  # Datasource properties
  datasource:
    url: jdbc:mysql://localhost:3306/SMART-CART-DB
    username: root
    password: rajeshwar3

  # ORM properties
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update